hcuv_job:
    pattern:  /
    defaults: { _controller: "HcuvJobeetBundle:Job:index" }

hcuv_job_show:
    pattern:  /{company}/{location}/{id}/{position}
    defaults: { _controller: "HcuvJobeetBundle:Job:show" }
    requirements:
      id: \d+
hcuv_job_preview:
    pattern:  /{company}/{location}/{token}/{position}
    defaults: { _controller: "HcuvJobeetBundle:Job:preview" }
    requirements:
        token:  \w+

hcuv_job_new:
    pattern:  /new
    defaults: { _controller: "HcuvJobeetBundle:Job:new" }

hcuv_job_create:
    pattern:  /create
    defaults: { _controller: "HcuvJobeetBundle:Job:create" }
    requirements: { _method: post }

hcuv_job_edit:
    pattern:  /{token}/edit
    defaults: { _controller: "HcuvJobeetBundle:Job:edit" }

hcuv_job_update:
    pattern:  /{token}/update
    defaults: { _controller: "HcuvJobeetBundle:Job:update" }
    requirements: { _method: post }

hcuv_job_delete:
    pattern:  /{token}/delete
    defaults: { _controller: "HcuvJobeetBundle:Job:delete" }
    requirements: { _method: post }

hcuv_job_publish:
    pattern:  /{token}/publish
    defaults: { _controller: "HcuvJobeetBundle:Job:publish" }
    requirements: { _method: post }