parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     jobeet
    database_user:     demo
    database_password: demo

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            N8Wvoek6KPwEI6onI692/.srbk06aZrb3pzuu/6
