security:
    firewalls:
        secured_area:
           pattern:    ^/
           anonymous: ~
           form_login:
               login_path:  /login
               check_path:  /login_check

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
        main:
            entity: { class: Hcuv\JobeetBundle\Entity\User, property: username }

    encoders:
        Hcuv\JobeetBundle\Entity\User: sha512