login:
    pattern:   /login
    defaults:  { _controller: HcuvJobeetBundle:Default:login }
login_check:
    pattern:   /login_check

HcuvJobeetBundle_category:
    pattern: /category/{slug}/{page}
    defaults: { _controller: HcuvJobeetBundle:Category:show, page: 1 }
HcuvJobeetBundle_hcuv_job:
        resource: "@HcuvJobeetBundle/Resources/config/routing/job.yml"
        prefix:   /job
HcuvJobeetBundle_homepage:
    pattern:  /
    defaults: { _controller: HcuvJobeetBundle:Job:index }
