HcuvJobeetBundle_hcuv_job:
        resource: "@HcuvJobeetBundle/Resources/config/routing/job.yml"
        prefix:   /job
HcuvJobeetBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: HcuvJobeetBundle:Default:index }
