HcuvJobeetBundle_category:
    pattern: /category/{slug}
    defaults: { _controller: HcuvJobeetBundle:Category:show }
HcuvJobeetBundle_hcuv_job:
        resource: "@HcuvJobeetBundle/Resources/config/routing/job.yml"
        prefix:   /job
HcuvJobeetBundle_homepage:
    pattern:  /
    defaults: { _controller: HcuvJobeetBundle:Job:index }
