parameters:
#    hcuv_jobeet.example.class: Hcuv\JobeetBundle\Example

services:
#    hcuv_jobeet.example:
#        class: %hcuv_jobeet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
